### ISSUE TITLE
Music Box Digster Error Python script, addon.py?

### ISSUE THREAD

**Issue by rlimas** [techdealer/plugin.audio.musicbox#29]
Hello, I am getting error when i access the Digster: Sections, Genre, Etc....
I could have sworn it initially worked on 12/20.  

I have tried different Machines, Intel, Linux, Android, (fresh 15.2 KODI)...no avail.

KODI LOG:
01:21:51 T:2595048256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.audio.musicbox/addon.py", line 1975, in <module>
                                                elif mode==3: Digster_sections()
                                              File "/home/osmc/.kodi/addons/plugin.audio.musicbox/addon.py", line 136, in Digster_sections
                                                decoded_data = json.loads(codigo_fonte)
                                              File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--

Is this known issue? or just me?

**Comment by techdealer** [comment]
Thank you for the report.

Looks like that some countries updated the site, and the universal api was deprecated in that new versions. I removed countries/domains that no longer work from the addon in the commit 5c355c0660ba5fb2c38025afb525e22431ff8cdf.
