### ISSUE TITLE
cookies.txt

### ISSUE THREAD

**Issue by RickG83** [techdealer/plugin.audio.musicbox#49]
After authentication (using VK) get an error to check the logs.  Looks like cookies.txt is not getting created.  It's not a write permissions issue on the directory.  Any idea how to solve?

17:54:42.717 T:1740108784   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', u'/home/osmc/.kodi/userdata/addon_data/plugin.audio.musicbox/cookies.txt')
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.audio.musicbox/addon.py", line 2002, in <module>
                                                if mode==None: Main_menu()
                                              File "/home/osmc/.kodi/addons/plugin.audio.musicbox/addon.py", line 87, in Main_menu
                                                validVKCookie = vkAuth.isCookieValid(VKCookie)
                                              File "/home/osmc/.kodi/addons/plugin.audio.musicbox/vkAuth.py", line 113, in isCookieValid
                                                cj.load(cookie)
                                              File "/usr/lib/python2.7/cookielib.py", line 1761, in load
                                                f = open(filename)
                                            IOError: (2, 'No such file or directory', u'/home/osmc/.kodi/userdata/addon_data/plugin.audio.musicbox/cookies.txt')
                                            -->End of Python script error report<--
17:54:42.881 T:1958581168   ERROR: GetDirectory - Error getting plugin://plugin.audio.musicbox/
17:54:42.881 T:1958581168   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.musicbox/) failed

**Comment by vsappel** [comment]
Same here. Kodi 17 Krypton
Openelec 8.0.0
